

security:

    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        users:
            entity: { class: AppBundle\Entity\User, property: email }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.secure.login_form

            logout:
                path: /logout

#    access_control:
#        - { path: ^/artist, roles: ROLE_ARTIST }