# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.save_file:
        class: AppBundle\Service\FileSaver
        arguments: ['%item_img_directory%']

    app.secure.login_form:
        class: AppBundle\Security\LoginAuthentication
        autowire: true

    app.doctrine.hash_password_listener:
        class: AppBundle\Doctrine\HashNakedPasswordListener
        autowire: true
        tags:
            - { name: doctrine.event_subscriber }